export enum ProjectColor {
  BERRY_RED = 'berry_red',
  RED = 'red',
  ORANGE = 'orange',
  YELLOW = 'yellow',
  OLIVE_GREEN = 'olive_green',
  LIME_GREEN = 'lime_green',
  GREEN = 'green',
  MINT_GREEN = 'mint_green',
  TEAL = 'teal',
  SKY_BLUE = 'sky_blue',
  LIGHT_BLUE = 'light_blue',
  BLUE = 'blue',
  GRAPE = 'grape',
  VIOLET = 'violet',
  LAVENDER = 'lavender',
  MAGENTA = 'magenta',
  SALMON = 'salmon',
  CHARCOAL = 'charcoal',
  GREY = 'grey',
  TAUPE = 'taupe',
}
